@host = http://
@dominio = localhost
@port = :3500
@endpoint = /users
@apiurl = {{host}}{{dominio}}{{port}}{{endpoint}}
@ContentType = application/json; charset=UTF-8

GET {{apiurl}}

###

GET {{apiurl}}/2

###
DELETE {{apiurl}}/4